# Generated by Django 5.1.2 on 2024-11-03 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockdata',
            old_name='ticker_symbol',
            new_name='ticker',
        ),
    ]
